### ISSUE TITLE
Wrap_content Flag not working 

### ISSUE THREAD

**Issue by AnchitAndroidWorld** [maxAman/MobikulAutoScrollView#2]
I just imported this library and tried editing the xml view part.

 set the layout hieght attribute to wrapContent and then also it is taking the flag of match parent.

![hieght_set_to_wrap_content](https://user-images.githubusercontent.com/33785707/32981796-4190c666-cca0-11e7-8a18-f5b45a4feaf6.jpg)

While on setting the hieght to some dps( say 100) it is working fine.
![hieght_set_to 100dp](https://user-images.githubusercontent.com/33785707/32981790-411ee91a-cca0-11e7-8519-44df619dc3de.jpg)

**Comment by maxAman** [comment]
This issue is also fixed.
